# TUESDAY 14TH OCTOBER, 2025

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [13]:
sb_data = pd.read_csv(r"superbowl.csv")
sb_data.head()

Super Bowl Coin Toss Outcome Coin Toss Winner Game Winner
0           1             Heads        Home Team   Home Team
1           2             Tails        Home Team   Away Team
2           3             Heads        Home Team   Home Team
3           4             Tails        Away Team   Home Team
4           5             Tails        Home Team   Away Team

In [23]:
coin_toss = sb_data["Coin Toss Winner"].value_counts()
coin_toss

Coin Toss Winner
Away Team    30
Home Team    25
Name: count, dtype: int64

In [25]:
expected

[27.5, 27.5]

In [26]:
observed_coin_toss = coin_toss.values
observed_coin_toss

array([30, 25])

In [27]:
coin_toss_chisquare = stats.chisquare(observed_coin_toss,expected)
coin_toss_chisquare

Power_divergenceResult(statistic=np.float64(0.45454545454545453), pvalue=np.float64(0.5001842570707944))

In [19]:
game_winner_count = sb_data["Game Winner"].value_counts()
game_winner_count

Game Winner
Away Team    31
Home Team    24
Name: count, dtype: int64

In [20]:
observed = game_winner_count.values
observed

array([31, 24])

In [21]:
expected = [sum(game_winner_count)/2, sum(game_winner_count)/2]
expected

[27.5, 27.5]

In [22]:
game_winner_chisquare = stats.chisquare(observed,expected)
game_winner_chisquare

Power_divergenceResult(statistic=np.float64(0.8909090909090909), pvalue=np.float64(0.34523107177184))

# WEDNESDAY 15TH OCTOBER, 2025

## GOODNESS OF FIT

In [3]:
nfl_data = pd.read_csv(r"nfl_games (1).csv")
nfl_data.head()

date  season  neutral  playoff team1 team2      elo1      elo2  \
0  1920-09-26    1920        0        0   RII   STP  1503.947  1300.000   
1  1920-10-03    1920        0        0   AKR   WHE  1503.420  1300.000   
2  1920-10-03    1920        0        0   RCH   ABU  1503.420  1300.000   
3  1920-10-03    1920        0        0   DAY   COL  1493.002  1504.908   
4  1920-10-03    1920        0        0   RII   MUN  1516.108  1478.004   

   elo_prob1  score1  score2  result1  
0   0.824651      48       0      1.0  
1   0.824212      43       0      1.0  
2   0.824212      10       0      1.0  
3   0.575819      14       0      1.0  
4   0.644171      45       0      1.0

In [6]:

# Narrow to relevant rows
nfl_data = nfl_data[(nfl_data["neutral"] == 0) & (nfl_data["playoff"] == 0) & (nfl_data["season"] >= 1966 )]
# Engineer a new feature
nfl_data.loc[nfl_data["result1"] == 0, "Game Winner"] = "Away Team"
nfl_data.loc[nfl_data["result1"] == 1, "Game Winner"] = "Home Team"

game_winner_counts_nfl = nfl_data["Game Winner"].value_counts().sort_index()
game_winner_counts_nfl

Game Winner
Away Team    5265
Home Team    7066
Name: count, dtype: int64

In [7]:
nfl_observed = game_winner_counts_nfl.values
nfl_observed

array([5265, 7066])

In [8]:
nfl_expected = [sum(game_winner_counts_nfl)/2,sum(game_winner_counts_nfl)/2]
nfl_expected

[6165.5, 6165.5]

In [10]:
nfl_chisquare = stats.chisquare(nfl_observed,nfl_expected)
nfl_chisquare

Power_divergenceResult(statistic=np.float64(263.0444408401589), pvalue=np.float64(3.723190824055013e-59))

## TEST FOR INDEPENDENCE

--- NULL HYPOTHESIS IS THAT THEY ARE NOT DEPENDENT ON EACH OTHER and ALTERNATIVE HYPOTHESIS IS THAT THEY ARE DEPENDENT ON EACH OTHER

In [14]:
independence_table = pd.crosstab(sb_data["Coin Toss Winner"], sb_data["Game Winner"])
independence_table

Game Winner       Away Team  Home Team
Coin Toss Winner                      
Away Team                15         15
Home Team                16          9

In [15]:
chi2, p, dof, xex = stats.chi2_contingency(independence_table)
print(chi2, p, dof, xex)

0.5920138888888885 0.44164141533080714 1 [[16.90909091 13.09090909]
 [14.09090909 10.90909091]]


--- we fail to reject the null hypothesis hence they have o relationship and are independent